openapi: 3.0.3
info:
  title: ROR Internal API
  description: The API is designed for ROR KBN plugin. It should be treated as internal. It means that backward compatibility won't be a first-class thing for us.
  version: 2.0.0

paths:
  /_readonlyrest/admin/config/test:
    get:
      summary: Getting currently applied Test Settings
      description: The endpoint can be used to fetch currently configured Test settings. If Test settings are not configured, the endpoint returns proper error.
      tags:
        - Test Settings
      parameters:
        - $ref: '#/components/parameters/XRorCorrelationIdHeader'
      responses:
        200:
          description: Contains currently configured Test Settings or business error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTestSettingsResponse'
              examples:
                TestSettingsAreConfiguredAndValidResponseExample:
                  $ref: "#/components/examples/TestSettingsAreConfiguredAndValidResponseExample"
                TestSettingsAreConfiguredAndValidButWithWarningsResponseExample:
                  $ref: "#/components/examples/TestSettingsAreConfiguredAndValidButWithWarningsResponseExample"
                TestSettingsNotConfiguredResponseExample:
                  $ref: "#/components/examples/TestSettingsNotConfiguredResponseExample"
                TestSettingsInvalidatedResponseExample:
                  $ref: "#/components/examples/TestSettingsInvalidatedResponseExample"
        403:
          description: The request was forbidden by ROR's ACL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenRorResponse'
              examples:
                NoAclBlockWasMatchedForbiddenResponseExample:
                  $ref: "#/components/examples/NoAclBlockWasMatchedForbiddenResponseExample"
                ForbidBlockMatchedResponseExample:
                  $ref: "#/components/examples/ForbidBlockMatchedResponseExample"
                TestSettingsNotConfiguredForbiddenResponseExample:
                  $ref: "#/components/examples/TestSettingsNotConfiguredForbiddenResponseExample"
                ImpersonationNotSupportedResponseExample:
                  $ref: "#/components/examples/ImpersonationNotSupportedResponseExample"
                ImpersonationNotAllowedResponseExample:
                  $ref: "#/components/examples/ImpersonationNotAllowedResponseExample"
                RorIsNotStartedYetResponseExample:
                  $ref: "#/components/examples/RorIsNotStartedYetResponseExample"
                RorFailedToStartResponseExample:
                  $ref: "#/components/examples/RorFailedToStartResponseExample"
    post:
      summary: Configuring Test Settings
      description: The endpoint can be used to configure Test Settings.
      tags:
        - Test Settings
      parameters:
        - $ref: '#/components/parameters/XRorCorrelationIdHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTestSettingsRequest'
      responses:
        200:
          description: Test Settings were configured or business error was returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateTestSettingsResponse'
              examples:
                TestSettingsUpdatedResponseExample:
                  $ref: "#/components/examples/TestSettingsUpdatedResponseExample"
                TestSettingsUpdateFailedResponseExample:
                  $ref: "#/components/examples/TestSettingsUpdateFailedResponseExample"
        403:
          description: The request was forbidden by ROR's ACL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenRorResponse'
              examples:
                NoAclBlockWasMatchedForbiddenResponseExample:
                  $ref: "#/components/examples/NoAclBlockWasMatchedForbiddenResponseExample"
                ForbidBlockMatchedResponseExample:
                  $ref: "#/components/examples/ForbidBlockMatchedResponseExample"
                TestSettingsNotConfiguredForbiddenResponseExample:
                  $ref: "#/components/examples/TestSettingsNotConfiguredForbiddenResponseExample"
                ImpersonationNotSupportedResponseExample:
                  $ref: "#/components/examples/ImpersonationNotSupportedResponseExample"
                ImpersonationNotAllowedResponseExample:
                  $ref: "#/components/examples/ImpersonationNotAllowedResponseExample"
                RorIsNotStartedYetResponseExample:
                  $ref: "#/components/examples/RorIsNotStartedYetResponseExample"
                RorFailedToStartResponseExample:
                  $ref: "#/components/examples/RorFailedToStartResponseExample"
    delete:
      summary: Invalidating Test Settings
      description: The endpoint can be used to invalidate Test Settings early
      tags:
        - Test Settings
      parameters:
        - $ref: '#/components/parameters/XRorCorrelationIdHeader'
      responses:
        200:
          description: Contains confirmation of Test Settings invalidation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidateTestSettingsResponse'
              examples:
                InvalidateTestSettingsSuccessResponseExample:
                  $ref: "#/components/examples/InvalidateTestSettingsSuccessResponseExample"
                InvalidateTestSettingsFailedResponseExample:
                  $ref: "#/components/examples/InvalidateTestSettingsFailedResponseExample"
        403:
          description: The request was forbidden by ROR's ACL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenRorResponse'
              examples:
                NoAclBlockWasMatchedForbiddenResponseExample:
                  $ref: "#/components/examples/NoAclBlockWasMatchedForbiddenResponseExample"
                ForbidBlockMatchedResponseExample:
                  $ref: "#/components/examples/ForbidBlockMatchedResponseExample"
                TestSettingsNotConfiguredForbiddenResponseExample:
                  $ref: "#/components/examples/TestSettingsNotConfiguredForbiddenResponseExample"
                ImpersonationNotSupportedResponseExample:
                  $ref: "#/components/examples/ImpersonationNotSupportedResponseExample"
                ImpersonationNotAllowedResponseExample:
                  $ref: "#/components/examples/ImpersonationNotAllowedResponseExample"
                RorIsNotStartedYetResponseExample:
                  $ref: "#/components/examples/RorIsNotStartedYetResponseExample"
                RorFailedToStartResponseExample:
                  $ref: "#/components/examples/RorFailedToStartResponseExample"
  /_readonlyrest/admin/config/test/localusers:
    get:
      summary: Getting list of local users
      description: The endpoint can be used to fetch local users' names defined in currently configured Test settings. If Test settings are not configured, the endpoint returns proper error.
      tags:
        - Test Settings
      parameters:
        - $ref: '#/components/parameters/XRorCorrelationIdHeader'
      responses:
        200:
          description: Contains local users or business error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetLocalUsersFromTestSettingsResponse'
              examples:
                GetLocalUsersFromTestSettingsResponseExample:
                  $ref: "#/components/examples/GetLocalUsersFromTestSettingsResponseExample"
                TestSettingsNotConfiguredResponseExample:
                  $ref: "#/components/examples/TestSettingsNotConfiguredResponseExample"
        403:
          description: The request was forbidden by ROR's ACL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenRorResponse'
              examples:
                NoAclBlockWasMatchedForbiddenResponseExample:
                  $ref: "#/components/examples/NoAclBlockWasMatchedForbiddenResponseExample"
                ForbidBlockMatchedResponseExample:
                  $ref: "#/components/examples/ForbidBlockMatchedResponseExample"
                TestSettingsNotConfiguredForbiddenResponseExample:
                  $ref: "#/components/examples/TestSettingsNotConfiguredForbiddenResponseExample"
                ImpersonationNotSupportedResponseExample:
                  $ref: "#/components/examples/ImpersonationNotSupportedResponseExample"
                ImpersonationNotAllowedResponseExample:
                  $ref: "#/components/examples/ImpersonationNotAllowedResponseExample"
                RorIsNotStartedYetResponseExample:
                  $ref: "#/components/examples/RorIsNotStartedYetResponseExample"
                RorFailedToStartResponseExample:
                  $ref: "#/components/examples/RorFailedToStartResponseExample"
  /_readonlyrest/admin/config/test/authmock:
    get:
      summary: Getting currently configured Auth Services mocks
      description: The endpoint can be used to fetch mocks for Auth Services defined in ReadonlyREST's Tests settings. If Test settings are not configured, the endpoint returns proper error.
      tags:
        - Test Settings
      parameters:
        - $ref: '#/components/parameters/XRorCorrelationIdHeader'
      responses:
        200:
          description: Contains authentication services mocks definitions or business error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAuthMocksResponse'
              examples:
                AllTypesOfAuthServicesConfiguredResponseExample:
                  $ref: "#/components/examples/AllTypesOfAuthServicesConfiguredResponseExample"
                NoAuthServiceConfiguredResponseExample:
                  $ref: "#/components/examples/NoAuthServiceConfiguredResponseExample"
                OnlySomeAuthServicesConfiguredResponseExample:
                  $ref: "#/components/examples/OnlySomeAuthServicesConfiguredResponseExample"
                TestSettingsNotConfiguredAuthServicesResponseExample:
                  $ref: "#/components/examples/TestSettingsNotConfiguredAuthServicesResponseExample"
                TestSettingsInvalidatedAuthServicesResponseExample:
                  $ref: "#/components/examples/TestSettingsInvalidatedAuthServicesResponseExample"
        403:
          description: The request was forbidden by ROR's ACL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenRorResponse'
              examples:
                NoAclBlockWasMatchedForbiddenResponseExample:
                  $ref: "#/components/examples/NoAclBlockWasMatchedForbiddenResponseExample"
                ForbidBlockMatchedResponseExample:
                  $ref: "#/components/examples/ForbidBlockMatchedResponseExample"
                TestSettingsNotConfiguredForbiddenResponseExample:
                  $ref: "#/components/examples/TestSettingsNotConfiguredForbiddenResponseExample"
                ImpersonationNotSupportedResponseExample:
                  $ref: "#/components/examples/ImpersonationNotSupportedResponseExample"
                ImpersonationNotAllowedResponseExample:
                  $ref: "#/components/examples/ImpersonationNotAllowedResponseExample"
                RorIsNotStartedYetResponseExample:
                  $ref: "#/components/examples/RorIsNotStartedYetResponseExample"
                RorFailedToStartResponseExample:
                  $ref: "#/components/examples/RorFailedToStartResponseExample"
    post:
      summary: Configuring Auth Services mocks
      description: The endpoint can be used to update mocks for Auth Services defined in ReadonlyREST's Tests settings. If Test settings are not configured, the endpoint returns proper error.
      tags:
        - Test Settings
      parameters:
        - $ref: '#/components/parameters/XRorCorrelationIdHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAuthMockRequest'
            examples:
              AllTypesOfAuthServicesConfiguredResponseExample:
                $ref: "#/components/examples/AllTypesOfAuthServicesConfiguredRequestExample"
              NoAuthServiceConfiguredResponseExample:
                $ref: "#/components/examples/NoAuthServiceConfiguredRequestExample"
              OnlySomeAuthServicesConfiguredResponseExample:
                $ref: "#/components/examples/OnlySomeAuthServicesConfiguredRequestExample"
      responses:
        200:
          description: Auth Services Mocks were configured or business error was returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateAuthMocksResponse'
              examples:
                AuthMocksUpdatedResponseExample:
                  $ref: "#/components/examples/AuthMocksUpdatedResponseExample"
                TestSettingsNotConfiguredAuthServicesResponseExample:
                  $ref: "#/components/examples/TestSettingsNotConfiguredAuthServicesResponseExample"
                TestSettingsInvalidatedAuthServicesResponseExample:
                  $ref: "#/components/examples/TestSettingsInvalidatedAuthServicesResponseExample"
                UnknownAuthServicesDetectedResponseExample:
                  $ref: "#/components/examples/UnknownAuthServicesDetectedResponseExample"
                AuthMocksUpdateFailedResponseExample:
                  $ref: "#/components/examples/AuthMocksUpdateFailedResponseExample"
        403:
          description: The request was forbidden by ROR's ACL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenRorResponse'
              examples:
                NoAclBlockWasMatchedForbiddenResponseExample:
                  $ref: "#/components/examples/NoAclBlockWasMatchedForbiddenResponseExample"
                ForbidBlockMatchedResponseExample:
                  $ref: "#/components/examples/ForbidBlockMatchedResponseExample"
                TestSettingsNotConfiguredForbiddenResponseExample:
                  $ref: "#/components/examples/TestSettingsNotConfiguredForbiddenResponseExample"
                ImpersonationNotSupportedResponseExample:
                  $ref: "#/components/examples/ImpersonationNotSupportedResponseExample"
                ImpersonationNotAllowedResponseExample:
                  $ref: "#/components/examples/ImpersonationNotAllowedResponseExample"
                RorIsNotStartedYetResponseExample:
                  $ref: "#/components/examples/RorIsNotStartedYetResponseExample"
                RorFailedToStartResponseExample:
                  $ref: "#/components/examples/RorFailedToStartResponseExample"

components:
  securitySchemes:
    http:
      type: http
      scheme: basic

  schemas:
    ForbiddenRorResponse:
      type: object
      required:
        - error
        - status
      properties:
        error:
          type: object
          required:
            - type
            - reason
            - due_to
          properties:
            type:
              type: string
              enum:
                - forbidden_response
            reason:
              type: string
              enum:
                - forbidden
            due_to:
              type: array
              description: |
                It's an array of causes why ROR's ACL forbade the request. 
                WARNING: Please notice, that one element array ES used to print as a string!!!
              items:
                type: string
                enum:
                  - OPERATION_NOT_ALLOWED
                  - FORBIDDEN_BY_BLOCK
                  - TEST_SETTINGS_NOT_CONFIGURED
                  - IMPERSONATION_NOT_SUPPORTED
                  - IMPERSONATION_NOT_ALLOWED
                  - READONLYREST_NOT_READY_YET
                  - READONLYREST_NOT_ENABLED
                  - READONLYREST_FAILED_TO_START
        status:
          type: number
          example: 403

    XRorCorrelationId:
      type: string
      description: "Correlation ID to correlate requests/responses logs within one ROR KBN session"
      example: "CED054A0-9881-401E-AEED-4FB4C5915DD6"

    GetTestSettingsResponse:
      oneOf:
        - $ref: '#/components/schemas/CurrentTestSettingsResponse'
        - $ref: '#/components/schemas/TestSettingsNotConfiguredResponse'
        - $ref: '#/components/schemas/TestSettingsInvalidatedResponse'
      discriminator:
        propertyName: status
        mapping:
          TEST_SETTINGS_PRESENT: '#/components/schemas/CurrentTestSettingsResponse'
          TEST_SETTINGS_NOT_CONFIGURED: '#/components/schemas/TestSettingsNotConfiguredResponse'
          TEST_SETTINGS_INVALIDATED: '#/components/schemas/TestSettingsInvalidatedResponse'

    TestSettingsNotConfiguredResponse:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          enum:
            - TEST_SETTINGS_NOT_CONFIGURED
        message:
          type: string
          description: Human readable message

    TestSettingsInvalidatedResponse:
      type: object
      required:
        - status
        - message
        - settings
        - ttl
      properties:
        status:
          type: string
          enum:
            - TEST_SETTINGS_INVALIDATED
        message:
          type: string
          description: Human readable message
        settings:
          type: string
          description: Recently configured Test Settings that are not longer valid, because they were invalidated
        ttl:
          $ref: '#/components/schemas/RorSettingsTtl'

    CurrentTestSettingsResponse:
      type: object
      required:
        - status
        - ttl
        - valid_to
        - settings
        - warnings
      properties:
        status:
          type: string
          enum:
            - TEST_SETTINGS_PRESENT
        ttl:
          $ref: '#/components/schemas/RorSettingsTtl'
        valid_to:
          type: string
          format: date-time
          description: "It says how long the Test Settings will be valid. After that date, the Settings will be invalidated"
          example: "2022-01-12T07:20:50.52Z"
        settings:
          $ref: '#/components/schemas/RorSettings'
        warnings:
          type: array
          items:
            $ref: '#/components/schemas/TestSettingsImpersonationWarnings'

    RorSettingsTtl:
      type: string
      description: "Configured ROR Settings Time To Live value. After this time the Test Setting will be automatically invalidated. Available units: d, day, h, hr, hour m, min, minute s, sec, second"
      example: 30 m

    TestSettingsImpersonationWarnings:
      description: "It warns about problems with impersonation in given block"
      type: object
      required:
        - block_name
        - rule_name
        - message
        - hint
      properties:
        block_name:
          type: string
          description: Block name in ROR's ACL
        rule_name:
          type: string
          description: Rule name in the block
        message:
          type: string
          description: It's human readable message with the fact what's wrong with that block and rule
        hint:
          type: string
          description: It's human readable message about possible solution of the problem

    UpdateTestSettingsRequest:
      type: object
      required:
        - ttl
        - settings
      properties:
        ttl:
          $ref: '#/components/schemas/RorSettingsTtl'
        settings:
          $ref: '#/components/schemas/RorSettings'

    UpdateTestSettingsResponse:
      oneOf:
        - $ref: '#/components/schemas/UpdateTestSettingsSuccessResponse'
        - $ref: '#/components/schemas/UpdateTestSettingsFailedResponse'
      discriminator:
        propertyName: status
        mapping:
          OK: '#/components/schemas/UpdateTestSettingsSuccessResponse'
          FAILED: '#/components/schemas/UpdateTestSettingsFailedResponse'

    UpdateTestSettingsSuccessResponse:
      type: object
      required:
        - status
        - message
        - valid_to
      properties:
        status:
          type: string
          enum:
            - OK
        message:
          type: string
          description: Human readable message
        valid_to:
          type: string
          format: date-time
          description: "It says how long the Test Settings will be valid. After that date, the Settings will be invalidated"
          example: "2022-01-12T07:20:50.52Z"

    UpdateTestSettingsFailedResponse:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          enum:
            - FAILED
        message:
          type: string
          description: Human readable message (cause)

    InvalidateTestSettingsResponse:
      oneOf:
        - $ref: '#/components/schemas/InvalidateTestSettingsSuccessResponse'
        - $ref: '#/components/schemas/InvalidateTestSettingsFailedResponse'
      discriminator:
        propertyName: status
        mapping:
          OK: '#/components/schemas/InvalidateTestSettingsSuccessResponse'
          FAILED: '#/components/schemas/InvalidateTestSettingsFailedResponse'

    InvalidateTestSettingsSuccessResponse:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          enum:
            - OK
        message:
          type: string
          description: Human readable message (cause)

    InvalidateTestSettingsFailedResponse:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          enum:
            - FAILED
        message:
          type: string
          description: Human readable message (cause)

    GetLocalUsersFromTestSettingsResponse:
      oneOf:
        - $ref: '#/components/schemas/GetLocalUsersFromPresentTestSettingsResponse'
        - $ref: '#/components/schemas/TestSettingsNotConfiguredResponse'
      discriminator:
        propertyName: status
        mapping:
          OK: '#/components/schemas/GetLocalUsersFromPresentTestSettingsResponse'
          TEST_SETTINGS_NOT_CONFIGURED: '#/components/schemas/TestSettingsNotConfiguredResponse'

    GetLocalUsersFromPresentTestSettingsResponse:
      type: object
      required:
        - status
        - users
      properties:
        status:
          type: string
          enum:
            - OK
        users:
          type: array
          description: It contains a list of locally (in ROR Settings) defined usernames.
          items:
            $ref: '#/components/schemas/LocalUserName'
        unknown_users:
          type: boolean
          description: It is 'true' when some usernames cannot be returned but they are defined (the users names cannot be resolved or exposed)

    LocalUserName:
      type: string
      description: Local user name
      example: John Doe

    GetAuthMocksResponse:
      oneOf:
        - $ref: '#/components/schemas/CurrentAuthMocksResponse'
        - $ref: '#/components/schemas/AuthMockTestSettingsNotConfiguredResponse'
        - $ref: '#/components/schemas/AuthMockTestSettingsInvalidatedResponse'
      discriminator:
        propertyName: status
        mapping:
          TEST_SETTINGS_PRESENT: '#/components/schemas/CurrentAuthMocksResponse'
          TEST_SETTINGS_NOT_CONFIGURED: '#/components/schemas/AuthMockTestSettingsNotConfiguredResponse'
          TEST_SETTINGS_INVALIDATED: '#/components/schemas/AuthMockTestSettingsInvalidatedResponse'

    CurrentAuthMocksResponse:
      type: object
      required:
        - status
        - services
      properties:
        status:
          type: string
          enum:
            - TEST_SETTINGS_PRESENT
        services:
          type: array
          items:
            $ref: '#/components/schemas/AuthMockService'

    AuthMockTestSettingsNotConfiguredResponse:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          enum:
            - TEST_SETTINGS_NOT_CONFIGURED
        message:
          type: string
          description: Human readable message

    AuthMockTestSettingsInvalidatedResponse:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          enum:
            - TEST_SETTINGS_INVALIDATED
        message:
          type: string
          description: Human readable message

    AuthMockUpdateFailedResponse:
      type: object
      required:
      properties:
        status:
          type: string
          enum:
            - FAILED
        message:
          type: string
          description: Human readable message

    UnknownAuthServicesDetectedResponse:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          enum:
            - UNKNOWN_AUTH_SERVICES_DETECTED
        message:
          type: string
          description: Human readable message

    UpdateAuthMockRequest:
      type: object
      required:
        - services
      properties:
        services:
          type: array
          items:
            $ref: '#/components/schemas/AuthMockService'

    UpdateAuthMocksResponse:
      oneOf:
        - $ref: '#/components/schemas/AuthMocksUpdatedResponse'
        - $ref: '#/components/schemas/AuthMockTestSettingsNotConfiguredResponse'
        - $ref: '#/components/schemas/AuthMockTestSettingsInvalidatedResponse'
        - $ref: '#/components/schemas/UnknownAuthServicesDetectedResponse'
        - $ref: '#/components/schemas/AuthMockUpdateFailedResponse'
      discriminator:
        propertyName: status
        mapping:
          OK: '#/components/schemas/AuthMocksUpdatedResponse'
          TEST_SETTINGS_NOT_CONFIGURED: '#/components/schemas/AuthMockTestSettingsNotConfiguredResponse'
          TEST_SETTINGS_INVALIDATED: '#/components/schemas/AuthMockTestSettingsInvalidatedResponse'
          UNKNOWN_AUTH_SERVICES_DETECTED: '#/components/schemas/UnknownAuthServicesDetectedResponse'
          FAILED: '#/components/schemas/AuthMockUpdateFailedResponse'

    AuthMocksUpdatedResponse:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          enum:
            - OK
        message:
          type: string
          description: Human readable message

    AuthMockService:
      oneOf:
        - $ref: '#/components/schemas/LdapAuthorizationService'
        - $ref: '#/components/schemas/ExternalAuthenticationService'
        - $ref: '#/components/schemas/ExternalAuthortizationService'
      discriminator:
        propertyName: type
        mapping:
          LDAP: '#/components/schemas/LdapAuthorizationService'
          EXT_AUTHN: '#/components/schemas/ExternalAuthenticationService'
          EXT_AUTHZ: '#/components/schemas/ExternalAuthortizationService'

    LdapAuthorizationService:
      type: object
      required:
        - type
        - name
      properties:
        type:
          type: string
          enum:
            - LDAP
        name:
          type: string
          description: Name of the LDAP connector defined in ReadonlyREST settings
          example: "LDAP 1"
        mock:
          oneOf:
            - $ref: '#/components/schemas/LdapAuthorizationServiceMock'
            - $ref: '#/components/schemas/MockServiceNotConfigured'

    LdapAuthorizationServiceMock:
      type: object
      required:
        - users
      properties:
        users:
          type: array
          description: The mock defines LDAP user and their roles (groups).
          items:
            $ref: '#/components/schemas/MockServiceUserAndGroups'

    ExternalAuthenticationService:
      type: object
      required:
        - type
        - name
      properties:
        type:
          type: string
          enum:
            - EXT_AUTHN
        name:
          type: string
          description: Name of the External Authentication Service defined in ReadonlyREST settings
          example: "Ext AuthN Service 1"
        mock:
          oneOf:
            - $ref: '#/components/schemas/ExternalAuthenticationServiceMock'
            - $ref: '#/components/schemas/MockServiceNotConfigured'

    ExternalAuthenticationServiceMock:
      type: object
      required:
        - users
      properties:
        users:
          type: array
          description: The mock defines External Authentication users.
          items:
            $ref: '#/components/schemas/MockServiceUsers'

    ExternalAuthortizationService:
      type: object
      required:
        - type
        - name
      properties:
        type:
          type: string
          enum:
            - LDAP
        name:
          type: string
          description: Name of the LDAP connector defined in ReadonlyREST settings
          example: "LDAP 1"
        mock:
          oneOf:
            - $ref: '#/components/schemas/ExternalAuthortizationServiceMock'
            - $ref: '#/components/schemas/MockServiceNotConfigured'

    ExternalAuthortizationServiceMock:
      type: object
      required:
        - users
      properties:
        users:
          type: array
          description: The mock defines External Grops Provider roles (groups) per user.
          items:
            $ref: '#/components/schemas/MockServiceUserAndGroups'

    MockServiceUserAndGroups:
      type: object
      description: It describes users and thier groups. Any of these users can be authenticated. The groups related to the authenticated user will be returned during authorization.
      required:
        - name
        - groups
      properties:
        name:
          $ref: '#/components/schemas/MockServiceUserName'
        groups:
          type: array
          description: Groups that the user belongs to
          items:
            $ref: '#/components/schemas/MockServiceUserGroup'

    MockServiceUsers:
      type: object
      description: It describes users. Any of these users can be authenticated.
      required:
        - name
      properties:
        name:
          $ref: '#/components/schemas/MockServiceUserName'

    MockServiceUserName:
      type: string
      description: Username returned by mocked Service
      example: John Doe

    MockServiceUserGroup:
      type: string
      description: User's group returned by mocked Service
      example:
        - Developer
        - Manager

    MockServiceNotConfigured:
      type: string
      enum:
        - NOT_CONFIGURED
      description: It means that given Service's mock has not been configured yet

    RorSettings:
      type: string
      description: ROR Settings escaped YAML
      example: |
        readonlyrest:\\r\\n    access_control_rules:\\r\\n\\r\\n    - name: | \\""Require HTTP Basic | Auth\\""\\r\\n      type: allow\\r\\n      indices: | [\\""test\\""]\\r\\n\\r\\n    - name: | \\""other\\""\\r\\n      auth_key: \\""admin:test\\""

  parameters:
    XRorCorrelationIdHeader:
      name: X-ROR-Correlation-ID
      in: header
      required: false
      description: ID to correlate requests/reponses logs within one ROR KBN session
      schema:
        $ref: '#/components/schemas/XRorCorrelationId'

  examples:

    NoAclBlockWasMatchedForbiddenResponseExample:
      summary: No ACL block was matched
      value:
        error:
          type: forbidden_response
          reason: forbidden
          due_to:
            - OPERATION_NOT_ALLOWED
        status: 403

    ForbidBlockMatchedResponseExample:
      summary: Request was forbidden by matching a block with "forbid" type
      value:
        error:
          type: forbidden_response
          reason: forbidden
          due_to:
            - FORBIDDEN_BY_BLOCK
        status: 403

    TestSettingsNotConfiguredForbiddenResponseExample:
      summary: Request was forbidden because impersonation feature is disbaled when Test Settings are not configured
      value:
        error:
          type: forbidden_response
          reason: forbidden
          due_to:
            - TEST_SETTINGS_NOT_CONFIGURED
        status: 403

    ImpersonationNotSupportedResponseExample:
      summary: No block was matched and at least one block has rule which doesn't support impersonation
      value:
        error:
          type: forbidden_response
          reason: forbidden
          due_to:
            - OPERATION_NOT_ALLOWED
            - IMPERSONATION_NOT_SUPPORTED
        status: 403

    ImpersonationNotAllowedResponseExample:
      summary: User has no impersonation permissions
      value:
        error:
          type: forbidden_response
          reason: forbidden
          due_to:
            - OPERATION_NOT_ALLOWED
            - IMPERSONATION_NOT_ALLOWED
        status: 403

    RorIsNotStartedYetResponseExample:
      summary: ROR was not started yet
      value:
        error:
          type: forbidden_response
          reason: forbidden
          due_to:
            - READONLYREST_NOT_READY_YET
        status: 403

    RorFailedToStartResponseExample:
      summary: ROR failed to start
      value:
        error:
          type: forbidden_response
          reason: forbidden
          due_to:
            - READONLYREST_FAILED_TO_START
        status: 403

    TestSettingsAreConfiguredAndValidResponseExample:
      summary: Test settings are configured and valid (no warnings)
      value:
        status: TEST_SETTINGS_PRESENT
        ttl: 30 m
        valid_to: "2022-01-12T07:20:50.52Z"
        settings: |
          readonlyrest:\\r\\n    access_control_rules:\\r\\n\\r\\n    - name: | \\""Require HTTP Basic | Auth\\""\\r\\n      type: allow\\r\\n      indices: | [\\""test\\""]\\r\\n\\r\\n    - name: | \\""other\\""\\r\\n      auth_key: \\""admin:test\\""
        warnings: []

    TestSettingsAreConfiguredAndValidButWithWarningsResponseExample:
      summary: Test settings are configured and valid (with warnings)
      value:
        status: TEST_SETTINGS_PRESENT
        ttl: 30 m
        valid_to: "2022-01-12T07:20:50.52Z"
        settings: |
          readonlyrest:\\r\\n    access_control_rules:\\r\\n\\r\\n    - name: | \\""Require HTTP Basic | Auth\\""\\r\\n      type: allow\\r\\n      indices: | [\\""test\\""]\\r\\n\\r\\n    - name: | \\""other\\""\\r\\n      auth_key_sha1: \\""d27aaf7fa3c1603948bb29b7339f2559dc02019a\\""
        warnings:
          - block_name: other
            rule_name: auth_key_sha1
            message: "The rule contains fully hashed username and password. It doesn't support impersonation in this configuration"
            hint: "You can use second version of the rule and use not hashed username. Like that: `auth_key_sha1: USER_NAME:hash(PASSWORD)"

    TestSettingsNotConfiguredResponseExample:
      summary: ROR Test settings are not configured yet
      value:
        status: TEST_SETTINGS_NOT_CONFIGURED
        message: ROR Test settings are not configured

    TestSettingsInvalidatedResponseExample:
      summary: ROR Test settings are invalidated
      value:
        status: TEST_SETTINGS_INVALIDATED
        message: ROR Test settings are invalidated
        recent_settings: |
          readonlyrest:\\r\\n    access_control_rules:\\r\\n\\r\\n    - name: | \\""Require HTTP Basic | Auth\\""\\r\\n      type: allow\\r\\n      indices: | [\\""test\\""]\\r\\n\\r\\n    - name: | \\""other\\""\\r\\n      auth_key: \\""admin:test\\""
        ttl: 30 m

    TestSettingsUpdatedResponseExample:
      summary: ROR Test settings was updated and configured with success
      value:
        status: OK
        message: updated settings
        valid_to: "2022-01-12T07:20:50.52Z"

    TestSettingsUpdateFailedResponseExample:
      summary: ROR Test settings update failed
      value:
        status: FAILED
        message: Current settings are already loaded

    InvalidateTestSettingsSuccessResponseExample:
      summary: ROR Test settings were invalidated
      value:
        status: OK
        message: test settings invalidated

    InvalidateTestSettingsFailedResponseExample:
      summary: ROR Test settings invalidation failed
      value:
        status: FAILED
        message: cannot invalidate test settings

    GetLocalUsersFromTestSettingsResponseExample:
      summary: Local users list response
      value:
        status: OK
        users:
          - john
          - tom
          - mark
        unknown_users: false

    AllTypesOfAuthServicesConfiguredResponseExample:
      summary: Three types of currently mockable Auth Services are configured
      value:
        status: TEST_SETTINGS_PRESENT
        services:
          - type: LDAP
            name: LDAP 1
            mock:
              users:
                - name: JohnDoe
                  groups:
                    - Developer
                    - DevOps
                - name: RobertSmith
                  groups:
                    - Manager
          - type: LDAP
            name: LDAP 2
            mock:
              users:
                - name: JohnDoe
                  groups:
                    - DevOps
                - name: JudyBrown
                  groups:
                    - Customer
          - type: EXT_AUTHN
            name: ACME1 External Authentication Service
            mock:
              users:
                - name: JaimeRhynes
                - name: MichaelDavis
                - name: Johny
          - type: EXT_AUTHZ
            name: ACME2 External Authorization Service
            mock:
              users:
                - name: JaimeRhynes
                  groups:
                    - Customer
                - name: Martian
                  groups:
                    - Visitor

    AllTypesOfAuthServicesConfiguredRequestExample:
      summary: Three types of currently mockable Auth Services are configured
      value:
        services:
          - type: LDAP
            name: LDAP 1
            mock:
              users:
                - name: JohnDoe
                  groups:
                    - Developer
                    - DevOps
                - name: RobertSmith
                  groups:
                    - Manager
          - type: LDAP
            name: LDAP 2
            mock:
              users:
                - name: JohnDoe
                  groups:
                    - DevOps
                - name: JudyBrown
                  groups:
                    - Customer
          - type: EXT_AUTHN
            name: ACME1 External Authentication Service
            mock:
              users:
                - name: JaimeRhynes
                - name: MichaelDavis
                - name: Johny
          - type: EXT_AUTHZ
            name: ACME2 External Authorization Service
            mock:
              users:
                - name: JaimeRhynes
                  groups:
                    - Customer
                - name: Martian
                  groups:
                    - Visitor

    NoAuthServiceConfiguredResponseExample:
      summary: Three types of currently mockable Auth Services are not configured yet
      value:
        status: TEST_SETTINGS_PRESENT
        services:
          - type: LDAP
            name: LDAP 1
            mock: NOT_CONFIGURED
          - type: LDAP
            name: LDAP 2
            mock: NOT_CONFIGURED
          - type: EXT_AUTHN
            name: ACME1 External Authentication Service
            mock: NOT_CONFIGURED
          - type: EXT_AUTHZ
            name: ACME2 External Authorization Service
            mock: NOT_CONFIGURED

    NoAuthServiceConfiguredRequestExample:
      summary: Three types of currently mockable Auth Services are not configured yet
      value:
        services:
          - type: LDAP
            name: LDAP 1
            mock: NOT_CONFIGURED
          - type: LDAP
            name: LDAP 2
            mock: NOT_CONFIGURED
          - type: EXT_AUTHN
            name: ACME1 External Authentication Service
            mock: NOT_CONFIGURED
          - type: EXT_AUTHZ
            name: ACME2 External Authorization Service
            mock: NOT_CONFIGURED

    OnlySomeAuthServicesConfiguredResponseExample:
      summary: Some of currently mockable Auth Services are configured
      value:
        status: TEST_SETTINGS_PRESENT
        services:
          - type: LDAP
            name: LDAP 1
            mock:
              users:
                - name: JohnDoe
                  groups:
                    - Developer
                    - DevOps
                - name: RobertSmith
                  groups:
                    - Manager
          - type: LDAP
            name: LDAP 2
            mock:
              users:
                - name: JohnDoe
                  groups:
                    - DevOps
                - name: JudyBrown
                  groups:
                    - Customer
          - type: EXT_AUTHN
            name: ACME1 External Authentication Service
            mock: NOT_CONFIGURED
          - type: EXT_AUTHZ
            name: ACME2 External Authorization Service
            mock: NOT_CONFIGURED

    OnlySomeAuthServicesConfiguredRequestExample:
      summary: Some of currently mockable Auth Services are configured
      value:
        services:
          - type: LDAP
            name: LDAP 1
            mock:
              users:
                - name: JohnDoe
                  groups:
                    - Developer
                    - DevOps
                - name: RobertSmith
                  groups:
                    - Manager
          - type: LDAP
            name: LDAP 2
            mock:
              users:
                - name: JohnDoe
                  groups:
                    - DevOps
                - name: JudyBrown
                  groups:
                    - Customer
          - type: EXT_AUTHN
            name: ACME1 External Authentication Service
            mock: NOT_CONFIGURED
          - type: EXT_AUTHZ
            name: ACME2 External Authorization Service
            mock: NOT_CONFIGURED

    TestSettingsNotConfiguredAuthServicesResponseExample:
      summary: ROR Test settings are not configured
      value:
        status: TEST_SETTINGS_NOT_CONFIGURED
        message: ROR Test settings are not configured. To use Auth Services Mock ROR has to have Test settings active.

    TestSettingsInvalidatedAuthServicesResponseExample:
      summary: ROR Test settings are invalidated
      value:
        status: TEST_SETTINGS_INVALIDATED
        message: ROR Test settings are invalidated. To use Auth Services Mock ROR has to have Test settings active.

    UnknownAuthServicesDetectedResponseExample:
      summary: Unknown Auth Services detected
      value:
        status: UNKNOWN_AUTH_SERVICES_DETECTED
        message: ROR doesn't allow to configure unknown Auth Services. Only the ones used in ROR's Test settings can be configured.

    AuthMocksUpdateFailedResponseExample:
      summary: Auth Services mocks update has failed
      value:
        status: FAILED
        message: 'Cannot save auth services mocks: Cannot save settings in index'

    AuthMocksUpdatedResponseExample:
      summary: Auth Services mocks were updated
      value:
        status: OK
        message: Auth Services mocks were updated

security:
  - http: []
